### ISSUE TITLE
Replace FlowRouter

### ISSUE THREAD

**Issue by jhigginbotham64** [Vize-Programming-Team/vize-meteor-app#113]
FlowRouter is a Meteor package. It must go.

I vote for react-router as a replacement, because we can start using it now and probably continue using it after we ditch Meteor: it's an NPM package for (AFAIK) pure React.

https://guide.meteor.com/react.html#using-react-router
https://www.npmjs.com/package/react-router

**Comment by joshuatshaffer** [comment]
I just looked into what we would need to do to migrate over. The biggest thing is that we will need to replace all of the `<a/>` tags with the `<Link/>` component from React Router. We should also move the header and footer out of the pages to make use of some of the features React Router has that Flow Router did not.

**Comment by jhigginbotham64** [comment]
Both of those sound very doable. There might be a nasty round of merge conflicts, but they should be easy enough to resolve.
Do you think this might also be a good time/place to refactor the href's to use the URL generators from router.jsx? I haven't gotten around to doing that yet, although I have no sense for whether it would be necessary with React Router.
