### ISSUE TITLE
Drop MongoDB use GraphQL instead

### ISSUE THREAD

**Issue by joshuatshaffer** [Vize-Programming-Team/vize-meteor-app#61]
MongoDB is not good for data integrity. We need to move to a more robust ACID relational database. We also need to implement a new client server API. We are going to use GraphQL for this.

**Comment by jhigginbotham64** [comment]
Can this be considered completed? With all the data migrated to PostgreSQL except the user accounts, the next steps to be taken on this issue involve replacing Meteor's methods with GraphQL mutations and traditional RPC's, and replacing Meteor's accounts system, which can be considered their own issues.
